### ISSUE TITLE
Support for ARM-based Big Sur

### ISSUE THREAD

**Issue by ShadowJonathan** [joerick/cibuildwheel#483] opened 2020-12-16 12:18 UTC
According to `packaging.tags` and macos wheel tagging, with the introduction of MacOS `11.0`, there's a new architecture to target; `arm64`

While `x86_64`-based MacOS 11+ targets will be able to support `10.*`, with ARM, it obviously wouldn't.

I couldn't find any issues or notes pointing out explicit support for this target (the compatibility matrix lists `MacOS x86_64` only, for example), so i'm making this one here to track development/support/comments for it.

**Comment by Czaki** [comment] 2020-12-16 12:36
The discussion started in #473. It partially depends on changes in wheel package. Its fixed release was published, so the work could slowly start.

**Comment by joerick** [comment] 2020-12-16 13:26
Closed as dupe of #473

**Closed by joerick** 2020-12-16 13:26 UTC

**Comment by ShadowJonathan** [comment] 2020-12-16 15:38
> Closed as dupe of #473

Thanks, I didn't definitively know if that other discussion had covered this.
