### ISSUE TITLE
macOS: `&&` turned into `'&&'`

### ISSUE THREAD

**Issue by madig** [joerick/cibuildwheel#80] opened 2018-07-04 14:24 UTC
I'm trying to run tests from the tests directory like so: `CIBW_TEST_COMMAND="cd {project}/tests && pytest --cov"`. This works on Travis' Linux CI but not on the macOS CI.

See e.g. https://travis-ci.org/adobe-type-tools/psautohint/jobs/400028035#L401

The upshot is that the command silently does nothing on the default macOS sh (bash would complain about too many args to `cd`).

**Comment by joerick** [comment] 2018-07-04 14:31
Duplicate of #39 (PRs welcome, this should be a pretty easy fix) :)

**Closed by joerick** 2018-07-04 14:31 UTC
