### ISSUE TITLE
The output of commands executed by shell() under Windows is hidden

### ISSUE THREAD

**Issue by lelit** [joerick/cibuildwheel#23] opened 2017-08-14 09:13 UTC
Is there a reason why the `shell()` method in `windows.py` uses `check_output()` instead of `check_call()` to execute subcommands? It was changed in commit f26da27db8cbe565860d432eebfea430f40a7dfb (actually PR #18), but it's not clear if it was fixing a problem or what...

I found this while investigating on one of the problems I annotated in issue #22: [changing it back](https://github.com/lelit/cibuildwheel/commit/2f7ac230f86888d82cd8a4cb960daa2d0c2b2153) to `check_call()` _magically_ solved the fact that the `pytest` call wasn't apparently executed, see https://ci.appveyor.com/project/lelit/python-rapidjson/build/1.0.29.

If @tgarc could check and confirm it wasn't intentional, I will open a PR.

**Comment by joerick** [comment] 2017-08-14 19:56
Ah, nice catch! I think at one point @tgarc was using the output of the `shell()` call, but that was eventually removed. Yes, a PR to resolve this would be excellent!

**Comment by joerick** [comment] 2017-08-14 19:59
Looks like @yannickjadoul beat me to the punch! This fix is included in his PR #24

**Comment by YannickJadoul** [comment] 2017-08-14 20:18
Oops, yeah, didn't see this issue. But I was fixing up output on Windows, already, so I though that was rather on topic in #24.

**Closed** 2017-08-14 20:35 UTC

**Comment by lelit** [comment] 2017-08-14 21:09
Sigh, trying with latest 0.4.1 I get [ValueError: can't have unbuffered text I/O](https://ci.appveyor.com/project/lelit/python-rapidjson/build/1.0.32#L40): should I change the way cibuildwheel is executed, using `python -u`?

**Comment by YannickJadoul** [comment] 2017-08-14 22:06
Are you using Python 3?
I can find this thread on SO: https://stackoverflow.com/questions/27067713/why-text-i-o-must-be-buffered-in-python-3

@joerick So maybe one of the solutions that explicitly calls `flush()` would be a better idea then (see #24). I hadn't thought of trying it with Python 3 since 2 is still the default on AppVeyor, but not supporting 3 seems not very future proof...

**Comment by joerick** [comment] 2017-08-14 22:07
Ah, looks like we need a python3 fix. Also I need to add that to our CI so that it's tested. In the meantime @lelit you could change to running cibuildwheel with Python 2 - it makes no difference to the wheels created.

**Comment by YannickJadoul** [comment] 2017-08-14 22:08
@lelit By the way, where does it give that error? Is that on the '-u' invocation or within cibuildwheel?

**Comment by lelit** [comment] 2017-08-14 22:18
Yes, I'm using Python 3. The problem appears within cibuildwheel, where the `sys.stdout` is replaced: `os.fdopen()` raises an error, when `buffering` is set to 0 and `mode` to `"w"`.

**Comment by lelit** [comment] 2017-08-14 22:25
@joerick, IIRC I could not use Python 2, because cibuildwheel runs `setup --name` to get the name of the package it is going to compile, and in my case that does not work because there's [a protection]( https://github.com/python-rapidjson/python-rapidjson/blob/master/setup.py#L20) in the setup.py to catch the case when one tries to build the package (Python 3 only) with Python 2, alerting the user.

**Comment by YannickJadoul** [comment] 2017-08-14 22:25
Right, thanks for that feedback! Then we know the problem isn't with the `-u`.

@joerick If you want, I listed the alternatives in #24, so you could see what seems best to you? (Though maybe there're still other possibilities though; I don't know.)

**Comment by lelit** [comment] 2017-08-14 22:27
Ideally, it should use the same target interpreter to execute that command, instead of `sys.executable`, in `__main__.py`...

**Comment by lelit** [comment] 2017-08-14 22:32
@YannickJadoul, maybe also the first hack proposed in the related [Python issue](http://bugs.python.org/issue17404) could be enough

**Comment by joerick** [comment] 2017-08-14 22:34
@YannickJadoul we can do a different solution for Python 3, if one is available. Otherwise, the manual `sys.stdout.flush()` isn't too bad, since there's only one `print` statement in the whole file.

**Comment by joerick** [comment] 2017-08-14 22:38
@lelit 

> Ideally, it should use the same target interpreter to execute that command

Which command do you mean? The `setup.py --name` command? How might that work?

**Comment by YannickJadoul** [comment] 2017-08-14 22:43
@lelit Wow, that's indeed a hack. Not all too sure I'm a big fan, but it's an option :-D

@joerick
> since there's only one `print` statement in the whole file.

What do you mean? There's quite a few of them in `windows.py` that also need to have this patch applied, no?

**Comment by joerick** [comment] 2017-08-14 22:48
As i look it's just the one - on [line 27](https://github.com/joerick/cibuildwheel/blob/master/cibuildwheel/windows.py#L27)

**Comment by joerick** [comment] 2017-08-14 22:49
The print to stderr should probably be changed to stdout on windows, given how violently it reacts to anything on stderr!

**Comment by lelit** [comment] 2017-08-15 07:52
> Which command do you mean? The setup.py --name command? How might that work?

At the time I didn't spend enough time on that to figure out a solution, but maybe we could delay the extraction of `package_name` and do that in the `build` method?

**Comment by YannickJadoul** [comment] 2017-08-15 09:57
@joerick Huh, yeah, you're right. I thought I'd seen more when I was looking, but I probably counted in those `shells` that actually all use the single `print`.

A more general, but more complicated solution is then this:
```Python
class Unbuffered(object):
   def __init__(self, stream):
       self.stream = stream
   def write(self, data):
       self.stream.write(data)
       self.stream.flush()
   def writelines(self, datas):
       self.stream.writelines(datas)
       self.stream.flush()
   def __getattr__(self, attr):
       return getattr(self.stream, attr)

import sys
sys.stdout = Unbuffered(sys.stdout)
```

**Comment by joerick** [comment] 2017-08-17 07:14
I like this other solution yannick, if that works with print and on 2&3 👍

**Comment by YannickJadoul** [comment] 2017-08-17 20:00
@joerick @lelit See #26, which is hopefully fixing that.
