### ISSUE TITLE
Test command fails using Cython

### ISSUE THREAD

**Issue by fredRos** [joerick/cibuildwheel#53] opened 2018-01-26 14:45 UTC
Thanks a lot for putting together this package, I think it's great idea to take the hassle out of building binary wheeels for multiple platforms. 

I ran into the issue that the tests have an import problem, links to the [detailed build log](https://travis-ci.org/fredRos/pypmc/jobs/333668064) and the [source code](https://github.com/fredRos/pypmc/pull/58)

I want to know what exactly is done. How is the binary wheel installed? Perhaps this could be clarified in the docs. I tried to recreate the problem on my development machine and did 
```
pip wheel . -w /tmp/built_wheel --no-deps # taken from the build log
pip install --user dist/pypmc-1.1.1-cp27-cp27mu-linux_x86_64.whl
```
I then ran the tests both in the source directory and the installed directory

```
nosetests 
nosetests /home/beaujean/.local/lib/python2.7/site-packages/pypmc
```
and both worked fine. So I don't understand why the tests don't work. Any idea?

```
...
+ sh -c 'nosetests /project'
E
======================================================================
ERROR: Failure: ImportError (cannot import name gauss)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/_internal/cpython-2.7.14-ucs2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/opt/_internal/cpython-2.7.14-ucs2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/opt/_internal/cpython-2.7.14-ucs2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/project/pypmc/__init__.py", line 9, in <module>
    from . import mix_adapt, density, sampler, tools
  File "/project/pypmc/mix_adapt/__init__.py", line 7, in <module>
    from . import hierarchical, variational, pmc, r_value
  File "/project/pypmc/mix_adapt/r_value.py", line 7, in <module>
    from ..tools._doc import _add_to_docstring
  File "/project/pypmc/tools/__init__.py", line 6, in <module>
    from ._partition import partition, patch_data
  File "/project/pypmc/tools/_partition.py", line 6, in <module>
    from ..density.gauss import Gauss
  File "/project/pypmc/density/__init__.py", line 6, in <module>
    from . import gauss, student_t, mixture, base
ImportError: cannot import name gauss
```

**Comment by YannickJadoul** [comment] 2018-01-28 12:24
Hmmm, weird, but it somehow seems as if Python and nose are trying to import your source directory (e.g., `File "/project/pypmc/__init__.py", line 9, in <module>`) instead of the installed one. (`print(pypmc.__file__)` can help you assure that and when this is the case)

What happens with `export CIBW_TEST_COMMAND="nosetests"` (since you're executing the command in the project directory anyway) ?

And what happens if you run `nosetests /project/dir` instead of the`nosetests` and `nosetests /home/beaujean/.local/lib/python2.7/site-packages/pypmc` that you have tested?

**Comment by joerick** [comment] 2018-02-05 21:55
This is a strange one - it feels like a bug in cibuildwheel, but I can't see it.

As for how the tests are run, cibuildwheel-

- builds the wheel, and delocates as necessary to embed shared libs
- installs that wheel into `site-packages` for the current python version
- moves away from the project directory (here we see it moving to `/root`) so that the tests will import the installed library, not the source repo.
- runs the test command with an absolute path to the project dir

**Comment by joerick** [comment] 2018-02-05 22:11
Ah, i think the problem is with the nose test importer and the use of relative import paths. If you want to use `nosetests` to test pypmc, you may have to move your tests into a separate directory tree and import the pypmc library using an absolute module import e.g. `from pypmc.density import gauss`.

Alternatively (I'm not sure how this works) you might get away with running the tests by passing a -_module_ name rather than a filename to nosetests - that should cause it to go looking in the site-packages first. e.g. `CIBW_TEST_COMMAND="nosetests pypmc"`

That said, I don't really understand why `nosetests` works on your local machine, when you're not telling Python how to read `.pyx` files. Do you know why that works? Have you already done an inline compile step in that case?

**Comment by fredRos** [comment] 2018-02-06 09:59
> moves away from the project directory (here we see it moving to /root) so that the tests will import the installed library, not the source rep

Yep, that must be it. I designed my tests so they can only be run in the source directory. That's convenient for development as it ignores any old version that may be around in the `site-packages`. But relative imports don't work on cibuildwheels with the installed version. I will have to fix that

**Comment by YannickJadoul** [comment] 2018-04-30 13:33
For the sake of bookkeeping and cleaning up: Is this issue solved, then? Can we close this issue, or is there still something to be fixed in `cibuildwheel`?

**Comment by joerick** [comment] 2018-06-18 22:29
Closing due to inactivity.

**Closed by joerick** 2018-06-18 22:29 UTC
